<a href="https://colab.research.google.com/github/fanyang2012/Mathematics/blob/main/Kopie_von_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mathematics in Python

In [1]:
import math

In [ ]:
dir(math)

In [ ]:
math.log10(100)

2.0

Function test

In [ ]:
def rest():
  x = input("x: ")
  y= int(x)/6
  return print(y)
rest = rest()

Test of "for loop" break and continue

"https://www.programiz.com/python-programming/break-continue"

In [ ]:
for i in "Hello World!": 
  if i == "r": 
    break
  print(i)
print("Great!")

In [ ]:
for i in "Hello World!": 
  if i == "r": 
    continue
  print(i)
print("Great!")

Numpy learning

In [2]:
import numpy as np

Traditional way to handel list operation

In [ ]:
def pysum():
  a = [0,1,2,3,4]
  b = [9,8,7,6,5]
  c=[]
  for i in range (len(a)):
    c.append(a[i]**2 + b[i]**3)
  return c
print(pysum())

[729, 513, 347, 225, 141]


numpy - nd.array

In [ ]:
def npsum():
  a = np.array([0,1,2,3,4])
  b = np.array([9,8,7,6,5])
  c = a ** 2 + b ** 3
  return c
print(npsum())

[729 513 347 225 141]


In [ ]:
  a = np.array([0,1,2,3,4])
  b = np.array([9,8,7,6,5])
  c = a ** 2 + b ** 3
  print(c)
  c.ndim
  c.shape
  c.size
  c.dtype

[729 513 347 225 141]


dtype('int64')

Create np.array

In [ ]:
def createArray(): 
  x = np.array([[1,2],[3,5],[0.1,0.2]], dtype= np.float32)
  y = np.arange(10)
  z = np.ones(shape=(3,5))
  a = np.zeros((4,6))
  b = np.full((2,3),6)
  c = np.eye(9)
  d = np.ones_like (a)
  e = np.zeros_like (a)
  f = np.full_like(a, 5)
  g = np.linspace(1,10,4)
  h = np.linspace (1,10,4,endpoint=False)
  i = np.concatenate((g,h))
  return print(x,y,z,a,b,c,d,e,f,g,h,i, sep="\n")
print(createArray())

In [ ]:
x = np.full((3,5),-5)
y = x.reshape((5,3))
z = x.swapaxes(0,1)
a = x.flatten()
print(x,y,z,a,sep="\n")

In [ ]:
np.sqrt(x)
np.abs(x)
np.square(x)

Numpy - Random generation

In [ ]:
ra = np.random.rand(3,5) # [0,1] uniform distribution
rb = np.random.randn(3,5) # standard normal distribution
rc = np.random.randint(100,200,(8,))
rd = np.random.choice(rc,(3,2),p = rc/np.sum(rc))
print(ra,rb,rc,rd,sep="\n")

In [ ]:
raa = np.random.uniform(0,10,(3,4)) # uniform distribution
rab = np.random.normal(5,0.2,(3,5)) # normal distribution
rac = np.random.poisson(2,(2,3)) # poission distribution
print(raa,rab,rac,sep="\n")

**Introduction - Matrix**

A matrix  (whose plural is matrices) is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns.

A matrix with m rows and n columns is called an m × n matrix or m-by-n matrix, where m and n are called the matrix dimensions.

element: An individual item in a matrix

row vector: A matrix with a single row

column vector: A matrix with a single column

square matrix: A matrix which has the same number of rows and columns

In [ ]:
M = np.array([[3,4],[-1,5]])
N = np.array([[2,8], [6,-2]])
Mrow = M[0,:] # row vector
Mcol = M[:,0] # column vector
print(Mrow)
print(Mcol)
print(M+N,M-N,M*N,M/N,3*M,2*N,sep="\n") # Arithematic Operations
print("1",M)
print("2", M * M)
print("3",pow(M,3)) # power of matrix
print("4",M @ M) # matrix multiplication
print("5",M.T) # matrix transpose
print("6",M @ M.T) # symmetric matrix

In [ ]:
  z = np.ones(shape=(3,3))
  a = np.zeros((4,4))
  b = np.full((2,3),6)
  c = np.eye(5)
  print(z,a,b,c, sep="\n")

**Matrix manipulation**: If 
A
 is an 
n
×
m
  matrix and 
B
 is an 
m
×
p
 matrix, the result 
A
B
 of their multiplication is an 
n
×
p
 matrix defined only if the number of columns 
m
 in 
A
 is equal to the number of rows 
m
 in 
B
.

In [ ]:
M = np.array([[3,4,-5],[-1,5,2]])
N = np.array([[2,8], [6,-2],[-6,9]])
print(M.shape) # 2 columns * 3 rows
print(M.size)
print(N.ndim)
print(M @ N) # matrix manipulation 3*2 matrix multiply by 2*3 matrix
print(N @ M) # Notice: M @ N != N @ M

Matrix Transpose

In [ ]:
M = np.array([[3,4],[-1,5]])
N = np.array([[2,8], [6,-2]])
print(M)
print(M.T)
print(M.T.T) # The transpose of transpose of matrix equals to matrix itself
print(M+N)
print((M+N).T)
print(M.T + N.T) # M.T + N.T = (M+N).T
(3 * M).T == 3 * M.T
print((M*N).T, M.T * N.T, sep="\n") 

Inverse of a Matrix

numpy.linalg.inv()

The inverse of A is A-1 only when:(I: Identity Matrix)

$$ A × A^{-1} = A^{-1} × A = I $$

Sometimes there is no inverse at all.

https://www.shuxuele.com/algebra/matrix-inverse.html

https://www.mathsisfun.com/algebra/matrix-inverse.html#:~:text=To%20find%20the%20inverse%20of,determinant%20(ad%2Dbc).

In [3]:
x = np.array([[3,4],[-1,5]])
ra = np.linalg.matrix_rank(x) # rank of matrix
y = np.linalg.inv(x) # inverse of matrix
print(x)
print(y)
print(ra)
print(x @ y) # Identitiy Matrix

[[ 3  4]
 [-1  5]]
[[ 0.26315789 -0.21052632]
 [ 0.05263158  0.15789474]]
2
[[1.00000000e+00 0.00000000e+00]
 [3.46944695e-17 1.00000000e+00]]


Rank and determinant of Identity Matrix

In [ ]:
rae = np.eye(5)
print(rae)
print(np.linalg.matrix_rank(rae))
print(np.linalg.det(rae)) # Determinant of matrix

In [ ]:
x = np.array([[3,4,9,2],[-1,5,2,3]])
print(x)
print(np.linalg.matrix_rank(x))